env:
  browser: true
  es2021: true
extends:
  - 'eslint:recommended'
  - "plugin:react/recommended"
  - "airbnb-base"
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
rules:
  no-console: 0
  import/extensions: 0
  react/react-in-jsx-scope: 0
  react/prop-types: 0